#tap 'caskroom/cask'
#tap 'caskroom/fonts'
# tap 'homebrew/bundle'
# tap 'homebrew/core'
# tap 'homebrew/services'
#brew 'ack'
brew 'antigen'
#brew 'git'
#brew 'ruby-build'
#brew 'rbenv'
#brew 'wget'
#brew 'zsh'
brew 'ruby-install'
brew 'chruby'
brew 'postgres'
cask 'iterm2'
# cask 'visual-studio-code'
# cask 'vlc'
cask 'atom'
cask 'sourcetree'
