tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/versions'
brew 'ack'
brew 'antigen'
# brew 'faac'
# brew 'ffmpeg'
# brew 'gdbm'
brew 'git'
# brew 'gh'
# brew 'graphviz'
# brew 'httpie'
# brew 'hub', args: ['HEAD']
# brew 'lame'
# brew 'libffi'
# brew 'libiconv'
# brew 'libpng'
# brew 'libyaml'
brew 'ngrok'
brew 'nvm'
# brew 'openssl'
# brew 'ossp-uuid'
# brew 'pcre'
# brew 'rcm'
# brew 'x264'
# brew 'xvid'
# brew 'xz'
# brew 'yasm'
brew 'wget'
brew 'zsh'
# cask 'dropbox'
# cask 'evernote'
# cask 'github'
cask 'google-chrome'
# cask 'google-drive'
# cask 'heroku-toolbelt'
cask 'iterm2'
# cask 'skitch'
# cask 'skype'
# cask 'slack'
# cask 'spotify'
# cask 'utorrent'
# cask 'virtualbox'
cask 'visual-studio-code'
# cask 'vlc'
