#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e
cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

GLOBAL_RUBY="$(cat .ruby-version)"
CURRENT_RUBY=$(rbenv global 2>/dev/null)
if ! [ $CURRENT_RUBY = $GLOBAL_RUBY ]; then
  echo "==> Installing ruby $GLOBAL_RUBY …"
  rbenv install --skip-existing
  echo "==> Setting rbenv global ruby to $GLOBAL_RUBY …"
  rbenv global $GLOBAL_RUBY
  rbenv rehash
fi

echo "==> Checking for bundler…"
which bundle >/dev/null 2>&1  || {
  echo "==> Installing bundler…"
  gem install bundler
  rbenv rehash
}

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    echo "Gemfile?"
    bundle install --path vendor/gems --quiet --without production
  }
fi
