#!/bin/bash

git fetch -p
branches=$(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}')

for branch in $branches
do 
  git branch -D $branch
done
